-- CREATE SCHEMA food

CREATE TABLE food.data_ibge (
    Codigo INT,
    descricacao_do_alimento NVARCHAR(255) NOT NULL,
    Categoria NVARCHAR(255) NOT NULL,
    Codigo_de_preparacao INT NULL,
    descricao_da_preparacao NVARCHAR(255) NOT NULL,
    Energia_kcal DECIMAL(10, 2) NULL,
    Proteina_g DECIMAL(10, 2) NULL,
    Lipidios_totais_g DECIMAL(10, 2) NULL,
    Carboidrato_g DECIMAL(10, 2) NULL,
    Fibra_alimentar_total_g DECIMAL(10, 2) NULL,
    Colesterol_mg DECIMAL(10, 2) NULL,
    AG_Saturados_g DECIMAL(10, 2) NULL,
    AG_Mono_g DECIMAL(10, 2) NULL,
    AG_Poli_g DECIMAL(10, 2) NULL,
    AG_Linoleico_g DECIMAL(10, 2) NULL,
    AG_Linolenico_g DECIMAL(10, 2) NULL,
    AG_Trans_total_g DECIMAL(10, 2) NULL,
    Acucar_total_g DECIMAL(10, 2) NULL,
    Acucar_de_adicacao_g DECIMAL(10, 2) NULL,
    Calcio_mg DECIMAL(10, 2) NULL,
    Magnesio_mg DECIMAL(10, 2) NULL,
    Manganes_mg DECIMAL(10, 2) NULL,
    Fosforo_mg DECIMAL(10, 2) NULL,
    Ferro_mg DECIMAL(10, 2) NULL,
    Sodio_mg DECIMAL(10, 2) NULL,
    Sodio_de_adicao_mg DECIMAL(10, 2) NULL,
    Potassio_mg DECIMAL(10, 2) NULL,
    Cobre_mg DECIMAL(10, 2) NULL,
    Zinco_mg DECIMAL(10, 2) NULL,
    Selenio_mcg DECIMAL(10, 2) NULL,
    Retinol_mcg DECIMAL(10, 2) NULL,
    Vitamina_A_RAE_mcg DECIMAL(10, 2) NULL,
    Tiamina_mg DECIMAL(10, 2) NULL,
    Riboflavina_mg DECIMAL(10, 2) NULL,
    Niacina_mg DECIMAL(10, 2) NULL,
    Niacina_NE_mg DECIMAL(10, 2) NULL,
    Piridoxina_mg DECIMAL(10, 2) NULL,
    Cobalami_na_mcg DECIMAL(10, 2) NULL,
    Folato_DFE_mcg DECIMAL(10, 2) NULL,
    Vitamina_D_mcg DECIMAL(10, 2) NULL,
    Vitamina_E_mg DECIMAL(10, 2) NULL,
    Vitamina_C_mg DECIMAL(10, 2) NULL
);